Repository Alfresco/alfresco-trashcan-cleaner-module, pull requests merged in 2021-04, with the labels that each got.

#7 ACS-1404 : Trashcan Cleaner job doesn't work when trying to delete from a big amount of data
  .gitignore
  README.md
  pom.xml
  src/main/java/org/alfresco/trashcan/TrashcanCleaner.java
  src/main/java/org/alfresco/trashcan/TrashcanCleanerJob.java
  src/test/java/org/alfresco/trashcan/TrashcanCleanerIT.java
  src/test/java/org/alfresco/trashcan/TrashcanCleanerTest.java
Labels: PR: unreviewed

#4 Readme keepPeriod sample throw an exception
  README.md
Labels: PR: reviewed-approved

#9 ACS-1473 Move Trashcan cleaner build to Travis
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  _ci/init.sh
  _ci/maven_release.sh
  _ci/settings.xml
  documentation/build-and-release-101.md
  pom.xml
  src/test/resources/log4j.properties
Labels: PR: partially-approved
